### ISSUE TITLE
No Single Column On Narrow Browser Window

### ISSUE THREAD

**Issue by mikjsmith** [axelhahn/flatpress-theme-touch-of-glass#1] opened 2019-09-30 16:16 UTC
Hi

Im using Touch of Glass which is set up for top menu and right menu. When I narrow the browser window to mimic a mobile device the articles eventually disappear however it remains a 2 column layout. Leggero 2 correctly drops to a single column, with the right menu moving below the articles.

Is this a bug in the responsive design?

thanks

mike

**Comment by axelhahn** [comment] 2019-11-10 23:03
Hi Mike

I didn't make the theme responsible yet.
In flatpress the articles are in a separate column where you cannot place any widget.
To get a "real" single column display you need to remove the widgets from left and right column. 

If I misunderstood something leave a reply, please.

Axel

**Comment by axelhahn** [comment] 2022-05-26 21:30
Hi @mikjsmith 

The theme got an update for responsive design. It will minify the left and right column on smaller screens and adds a hamburger menu to show them. If you still use flatpress maybe you wanna give it a try.
Replace the subfolder "atog" below ./fp-interface/themes/ with the content of the current repository. In the webbrowser press shift + reload to override the browser cache.

Axel

**Comment by mikjsmith** [comment] 2022-05-29 13:10
Hi @axelhahn 

This works really well :) I cant see any obvious bugs at the moment - it is live on my site and works well.

Only comment is around mobile devices that request a mobile version of the site. This presents an unstyled text version of the site, which is the same for all themes.

Is this an issue with FlatPress?

thanks

mike

**Comment by axelhahn** [comment] 2022-06-01 22:21
Hi @mikjsmith 
In my environment I cannot reproduce a problem while commenting something. And didn't hear about it before. If the looses its styling it should happen on mobile devices and Desktop (because both versions load the same code and styling from the server). 
How can I reproduce it? Does it happen on your website? 
Axel

**Comment by mikjsmith** [comment] 2022-06-05 14:04
Hi @axelhahn 

Here is my site: https://www.lecturematerials.co.uk/

Here are two screenshots from my phone showing accessing the site using the Vivaldi browser (and also Chrome) to switch between Mobile and Desktop

![Screenshot_2022-06-05-14-55-33-103_com vivaldi browser](https://user-images.githubusercontent.com/3380838/172054444-aae6acb1-6671-4626-85d3-429ce188a6fc.jpg)

![Screenshot_2022-06-05-14-55-45-263_com vivaldi browser](https://user-images.githubusercontent.com/3380838/172054454-971ac2af-3655-442c-9bf2-5453c155ae8e.jpg)

**Comment by axelhahn** [comment] 2022-06-10 20:40
Hi @mikjsmith ,

your described behaviour has nothing to do with the theme. If you try https://www.axel-hahn.de/blog/ that does use the same theme doesn't have the problem.

I verified and reproduced the switching to the no-css look with the developer tools on a desktop browser. 

The problem is: Your server sends back different html code to the client. 

As a **desktop browser**: html code with theme atog

```html
<!DOCTYPE html>
<html>
<head>
    
	<title>Spaced-OoooO-Out</title>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1">
	
	<meta name="Robots" content="noindex, follow">
       ...
       <link media="screen" href="(...)/themes/atog/blue/res/style.css" type="text/css" rel="stylesheet" />
       ...

```

If I switch to a mobile device and reload it is html with leggero theme (it not just a erplacement of theme css files - the code comes from a complete different template):

```html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en-us">
<head>
	<title>Spaced-OoooO-Out</title>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<link href='[http://fonts.googleapis.com/css?family=Open+Sans:400italic,700italic,400,700](view-source:http://fonts.googleapis.com/css?family=Open+Sans:400italic,700italic,400,700)' rel='stylesheet' type='text/css'/>
       ...
       <link media="screen,projection,handheld" href="(...)themes/leggero/res/style.css" type="text/css" rel="stylesheet" />
       ...
```
The page has no-css like feeling because the leggero css file does not exist.

I compared the difference of both request headers. It is the usaer agent:

* User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:101.0) Gecko/20100101 Firefox/101.0 vs.
* User-Agent: Mozilla/5.0 (Linux; Android 11; SAMSUNG SM-G973U) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/14.2 Chrome/87.0.4280.141 Mobile Safari/537.36

I guess you have a proxy or a rule in your webserver that switches something by the user agent requesting a page. 

regards,
Axel

**Comment by axelhahn** [comment] 2022-06-23 21:59
I close the issue.

**Closed as completed by axelhahn** 2022-06-23 21:59 UTC
